package net.xdevelop.template.bank.model;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    private long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.user_id
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.amount
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    private double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.created_date
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    private long createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_modified_date
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    private long lastModifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.user_id
     *
     * @return the value of account.user_id
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.user_id
     *
     * @param userId the value for account.user_id
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.amount
     *
     * @return the value of account.amount
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    public double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.amount
     *
     * @param amount the value for account.amount
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    public void setAmount(double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.created_date
     *
     * @return the value of account.created_date
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    public long getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.created_date
     *
     * @param createdDate the value for account.created_date
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    public void setCreatedDate(Long createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_modified_date
     *
     * @return the value of account.last_modified_date
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    public long getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_modified_date
     *
     * @param lastModifiedDate the value for account.last_modified_date
     *
     * @mbg.generated Sun Aug 05 15:59:06 CST 2018
     */
    public void setLastModifiedDate(Long lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}